name: build

on:
  push:
    paths-ignore:
      - "**.md"
      - LICENSE
      - .github/FUNDING.yml
    branches: [main, dev]
  pull_request:
    paths-ignore:
      - "**.md"
      - LICENSE
      - .github/FUNDING.yml
    branches: [main]

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Installing Node Dependencies
        run: |
          rm -rf node_modules yarn.lock
          yarn install --frozen-lockfile
        continue-on-error: false

      - name: Print cbmp version
        run: npx cbmp --version

      - name: Rendering Bitmaps
        run: yarn render
        continue-on-error: false

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Installing PyPi Dependencies
        run: python -m pip install --upgrade pip clickgen
        continue-on-error: false

      - name: Print clickgen Version
        run: |
          clickgen --version
          ctgen --version

      - name: Building `Bibata Modern Amber` Cursors
        run: ctgen build.toml -n 'Bibata-Modern-Amber' -c 'Yellowish and rounded edge Bibata cursors.' -d 'bitmaps/Bibata-Modern-Amber'

      - name: Building `Bibata Original Amber` Cursors
        run: ctgen build.toml -n 'Bibata-Original-Amber' -c 'Yellowish and sharp edge Bibata cursors.' -d 'bitmaps/Bibata-Original-Amber'

      - name: Building `Bibata Modern Classic` Cursors
        run: ctgen build.toml -n 'Bibata-Modern-Classic' -c 'Black and rounded edge Bibata cursors.' -d 'bitmaps/Bibata-Modern-Classic'

      - name: Building `Bibata Original Classic` Cursors
        run: ctgen build.toml -n 'Bibata-Original-Classic' -c 'Black and sharp edge Bibata cursors.' -d 'bitmaps/Bibata-Original-Classic'

      - name: Building `Bibata Modern Ice` Cursors
        run: ctgen build.toml -n 'Bibata-Modern-Ice' -c 'White and rounded edge Bibata cursors.' -d 'bitmaps/Bibata-Modern-Ice'

      - name: Building `Bibata Original Ice` Cursors
        run: ctgen build.toml -n 'Bibata-Original-Ice' -c 'White and sharp edge Bibata cursors.' -d 'bitmaps/Bibata-Original-Ice'

      - name: Building `Bibata Modern Amber Right` Cursors
        run: ctgen build.right.toml -n 'Bibata-Modern-Amber-Right' -c 'Yellowish and rounded edge right-hand Bibata cursor.' -d 'bitmaps/Bibata-Modern-Amber-Right'

      - name: Building `Bibata Original Amber Right` Cursors
        run: ctgen build.right.toml -n 'Bibata-Original-Amber-Right' -c 'Yellowish and sharp edge right-hand Bibata cursor.' -d 'bitmaps/Bibata-Original-Amber-Right'

      - name: Building `Bibata Modern Classic Right` Cursors
        run: ctgen build.right.toml -n 'Bibata-Modern-Classic-Right' -c 'Black and rounded edge right-hand Bibata cursor.' -d 'bitmaps/Bibata-Modern-Classic-Right'

      - name: Building `Bibata Original Classic Right` Cursors
        run: ctgen build.right.toml -n 'Bibata-Original-Classic-Right' -c 'Black and sharp edge right-hand Bibata cursor.' -d 'bitmaps/Bibata-Original-Classic-Right'

      - name: Building `Bibata Modern Ice Right` Cursors
        run: ctgen build.right.toml -n 'Bibata-Modern-Ice-Right' -c 'White and rounded edge right-hand Bibata cursor.' -d 'bitmaps/Bibata-Modern-Ice-Right'

      - name: Building `Bibata Original Ice Right` Cursors
        run: ctgen build.right.toml -n 'Bibata-Original-Ice-Right' -c 'White and sharp edge right-hand Bibata cursor.' -d 'bitmaps/Bibata-Original-Ice-Right'
